server: 
  port: 10005
  
spring: 
  application: 
    name: service-fegin
  
eureka:
  client:  
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/  
      
feign: 
  hystrix: 
    enabled: true 