server:
  port: 10101
  
spring:
  application: 
    name: eurake-hello  
  cloud:
    discovery:
      enabled: true
    config:
      uri: http://localhost:8888/
      profile: hello1
      
eureka:
  client:  
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/  

